# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(210, 40, 301, 61))
        self.Title.setObjectName("Title")
        self.Kp_slider = QtWidgets.QSlider(self.centralwidget)
        self.Kp_slider.setGeometry(QtCore.QRect(10, 190, 541, 81))
        self.Kp_slider.setMaximum(100)
        self.Kp_slider.setOrientation(QtCore.Qt.Horizontal)
        self.Kp_slider.setObjectName("Kp_slider")
        self.Kp_name = QtWidgets.QLabel(self.centralwidget)
        self.Kp_name.setGeometry(QtCore.QRect(560, 220, 67, 17))
        self.Kp_name.setObjectName("Kp_name")
        self.Kp_value = QtWidgets.QLabel(self.centralwidget)
        self.Kp_value.setGeometry(QtCore.QRect(595, 220, 41, 20))
        self.Kp_value.setObjectName("Kp_value")
        self.Ki_slider = QtWidgets.QSlider(self.centralwidget)
        self.Ki_slider.setGeometry(QtCore.QRect(10, 260, 541, 81))
        self.Ki_slider.setMaximum(100)
        self.Ki_slider.setOrientation(QtCore.Qt.Horizontal)
        self.Ki_slider.setObjectName("Ki_slider")
        self.Ki_value = QtWidgets.QLabel(self.centralwidget)
        self.Ki_value.setGeometry(QtCore.QRect(600, 290, 41, 20))
        self.Ki_value.setObjectName("Ki_value")
        self.Ki_name = QtWidgets.QLabel(self.centralwidget)
        self.Ki_name.setGeometry(QtCore.QRect(556, 290, 71, 20))
        self.Ki_name.setObjectName("Ki_name")
        self.Kd_slider = QtWidgets.QSlider(self.centralwidget)
        self.Kd_slider.setGeometry(QtCore.QRect(10, 340, 541, 81))
        self.Kd_slider.setMaximum(100)
        self.Kd_slider.setOrientation(QtCore.Qt.Horizontal)
        self.Kd_slider.setObjectName("Kd_slider")
        self.Kd_value = QtWidgets.QLabel(self.centralwidget)
        self.Kd_value.setGeometry(QtCore.QRect(600, 370, 67, 17))
        self.Kd_value.setObjectName("Kd_value")
        self.Kd_name = QtWidgets.QLabel(self.centralwidget)
        self.Kd_name.setGeometry(QtCore.QRect(560, 370, 67, 17))
        self.Kd_name.setObjectName("Kd_name")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title.setText(_translate("MainWindow", "Ajuste de parametros del controlador PID"))
        self.Kp_name.setText(_translate("MainWindow", "Kp"))
        self.Kp_value.setText(_translate("MainWindow", "0"))
        self.Ki_value.setText(_translate("MainWindow", "0"))
        self.Ki_name.setText(_translate("MainWindow", "Ki"))
        self.Kd_value.setText(_translate("MainWindow", "0"))
        self.Kd_name.setText(_translate("MainWindow", "Kd"))
